spring:
  profiles:
    active: dev
  application:
    name: ebuy
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ebuy
    username: foo
    password: bar
    driverClassName: org.postgresql.Driver
